# Generated by Django 3.2.12 on 2024-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('teacherId', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
