# Generated by Django 3.2.12 on 2024-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_description', models.CharField(max_length=20)),
                ('course_level', models.CharField(max_length=20)),
                ('course_duration', models.PositiveSmallIntegerField()),
                ('course_objective', models.CharField(max_length=20)),
                ('course_module', models.CharField(max_length=20)),
                ('course_prior_skills', models.CharField(max_length=20)),
                ('course_attendance', models.PositiveSmallIntegerField()),
                ('course_learning_material', models.CharField(max_length=20)),
                ('course_trainer', models.CharField(max_length=20)),
            ],
        ),
    ]
