# Generated by Django 3.2.12 on 2024-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_color', models.CharField(max_length=20)),
                ('class_building_material', models.CharField(max_length=20)),
                ('class_size', models.CharField(max_length=20)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('class_lightning', models.CharField(max_length=20)),
                ('class_temperature', models.CharField(max_length=20)),
                ('class_odor', models.CharField(max_length=20)),
                ('class_comfort', models.CharField(max_length=20)),
                ('class_state', models.CharField(max_length=20)),
            ],
        ),
    ]
